docker setup
Ingsis-Group-4/snippet-manager pull request #2
Opened 2024-05-11 20:40 UTC by cataghiglione

2024-05-14 00:02 UTC, MatiBrego approved these changes

2024-05-14 21:03 UTC, JuanSeZ requested changes

2024-05-14 21:03 UTC, JuanSeZ commented on volumes/s3-storage/.localstack/server.test.pem
Esto no va

2024-05-15 09:34 UTC, MatiBrego commented on volumes/s3-storage/.localstack/server.test.pem
English please

2024-05-15 20:48 UTC, JuanSeZ requested changes

2024-05-15 20:48 UTC, JuanSeZ commented on volumes/s3-storage/.localstack/server.test.pem
Are we still using this ?

2024-05-16 00:39 UTC, MatiBrego approved these changes

2024-05-16 00:40 UTC, merged